### ISSUE TITLE
Rip-Off of ReconDog

### ISSUE THREAD

**Issue by UltimateHackers** [Manisso/Crips#2]
Ripping off someone's program for fame and shit isn't cool bro.
**Crips** is a clear rip off of **[ReconDog](https://github.com/UltimateHackers/ReconDog)**
Grow up.

**Comment by Manisso** [comment]
@UltimateHackers  i didn't Know That You Have A Tools Named ReconDog
I Just Found This api and Use it for my self :/

**Comment by Beyarz** [comment]
ReconDog & Crips seems to do the exact same thing but the source code looks very different from each other. I would not call this a ripp off just 2 different projects with the same purpose.

**Comment by Manisso** [comment]
@Beyarz 
Yes i Found The API On Internet and i worked On It :100:  But Sorry @UltimateHackers  if the Script disturb you

**Comment by UltimateHackers** [comment]
k
