### ISSUE TITLE
api amount error

### ISSUE THREAD

**Issue by azamet90** [Manisso/Crips#3]
i like your script it is very useful but i get api amount exected or something like that error how to fix it or do you need to fix it maybe?

**Comment by Manisso** [comment]
Thank you Bro for this report but it seems that there is no problem in the API
~ make sure you have a good internet connection
~ check the validity of the target
# Crips Only works with an internet connection and can not scan a local host or local IP address
* if the problem persists send us a screenshot

**Comment by azamet90** [comment]
after i run it with sudo problem was fixed
